Migration Plugin Update
ClassicPress/ClassicPress-Migration-Plugin pull request #103
Opened 2024-03-12 14:33 UTC by EliteStarServices

- Adjust checks, notifications and information text as needed for CP v2
- Warn that Migration requires Re-Install (reminder if you go back into the plugin)
- Chat link changed from Slack to Zulip
- Add smart drop down to Advanced Controls
- Offer CP v1 & v2 current and one version back (unless no previous as with 2 right now)
- Offer WP current, 6.3.x and 4.9.x (4.9 offered only if running php7)
- Offer release version if running CP migration version
- Will not offer what you already have
- Suggest CP Default theme (temporary hard coded - API needs adjustment)

2024-03-12 15:31 UTC, xxsimoxx commented on lib/admin-page.php
> +						'If no longer needed. you can <a href="%s">delete the plugin</a>.',
If no longer needed you

2024-03-12 15:35 UTC, xxsimoxx commented on lib/admin-page.php
> +			'It looks like you are using the <strong>%1$s</strong> theme. Unfortunately, %1$s is known to be incompatible with ClassicPress.%2$s',
Why %2$s is used?

2024-03-13 15:07 UTC, xxsimoxx requested changes
I have a site that can't access ClassicPress API.
In this case the plugin fails and don't display the "Advanced Version Control Tool", where the "Build URL:" is very useful in this scenario (it's the only way to update a site with this problem).

2024-03-13 15:13 UTC, EliteStarServices commented
That was existing functionality, but can be changed.
How do I add to an existing PR, just push my local again and github will see more changes??

2024-03-14 07:03 UTC, xxsimoxx approved these changes

2024-03-14 16:52 UTC, xxsimoxx approved these changes

2024-03-14 16:52 UTC, xxsimoxx commented on lib/admin-page.php
>  	// TEMPORARY HARD CODED DEFAULT THEME
Please remove the comment also.

2024-03-14 17:08 UTC, merged